### ISSUE TITLE
Complete map rotation

### ISSUE THREAD

**Issue by Chronitonity** [WhiteFox08/R-Server#2]
Figure this out sometime whitefox

**Comment by WhiteFox08** [comment]
#99e23b3dcca230c8bb8ab16610ff76b105148a0f

**Comment by WhiteFox08** [comment]
Population and vote weight values are up for discussion.

**Comment by WhiteFox08** [comment]
Configuration's are serverside only. Should be good to go!

**Comment by Chronitonity** [comment]
nani
